#pragma once
#define DESK_CAP_RETURN_OK		0
#define DESK_CAP_RETURN_ERROR	1
#define DESK_CAP_CREATE_MP4_FILE_ERROR		(DESK_CAP_RETURN_OK+100)
#define DESK_CAP_OPEN_AUDIO_CAP_ERROR		(DESK_CAP_RETURN_OK+101)